# Numpy

We will be learning about some basic programming and data analysis using Numpy and Pandas. First up - NumPy

NumPy is the fundamental package for scientific computing in Python. It is used across many fields inc. Mathematics, Engineering, Finance, Data Science, Artificial Intelligence, Machine Learning etc. Most scientific computing libraries will build on NumPy.

Numpy provides functions to work with N-dimensional arrays and an assortment of routines for fast operations on such arrays: matrix mathematics, logical, shape manipulation, statistical operations, random simulation etc.

## Basic Numpy tools

<img src="https://matteding.github.io/images/broadcasting-3d-scalar.gif" width="400" height="400" align="left"/>


Here, we will exam some fairly simple tools in Numpy for the management of data and doing basic statistics. First, lets make sure numpy is imported:


In [1]:
import numpy as np

### Array creation and Indexing

In the cells below we will learn basic array creation and indexing


In [2]:
a = np.array([1, 2, 3])            # Create a simple array
print("Numpy Array 'a':\n")
print(type(a))                     # Prints type as recognised by Python
print(a.shape)                     # Prints its shape
print(a[0], a[1], a[2])            # Prints certain indexed values
a[0] = 5                           # Change an element of the array
print(a,"\n")                   


print("Numpy Array 'b':\n")
b = np.array([[1,2,3],[4,5,6]])    # Create an array with more 'complexity'
print(b.shape)
print(b)                     
print(b[0, 0], b[0, 1], b[1, 0])  


Numpy Array 'a':

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3] 

Numpy Array 'b':

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


### Array manipulation and mathematics
Where numpy gets really powerful is its efficiency in array manipulation and mathematics.

In [3]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y,'\n')
print(x * y,'\n') 

# numpy has many mathematical functions built in - accessed via dot notation
print(np.sqrt(x),'\n')
print(np.dot(x, y),'\n')
print(np.cross(x, y),'\n')

[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[19 22]
 [43 50]] 

[-4 -4] 



/var/folders/qd/jm_fm64927g3y1crrgxmb0g80000gn/T/ipykernel_78238/15743206.py:10: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x, y),'\n')


Numpy also provides aggregation methods.

In [4]:
print(x.sum())  # sum over the entire matrix
print(y.mean(axis=1))  # mean of each row

10
[5.5 7.5]


## Activity
Your turn... <br>
Add comments that explain what your code is doing

#### 1) Create the following 3 x 4 array and call it 'c'

[[ 1  2  3  4] <br>
 [ 5  6  7  8] <br>
 [ 9 10 11 12]] <br>

In [ ]:
# Create the following 3 x 4 array and call it 'c':
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #use the numpy array function to define the array
c # printing array so i can inspect it

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 2) Print all values in rows 2 & 3

In [39]:
# Print all values in rows 2 & 3
print("Numpy rows 2 # 3 in 'c' \n")
print("print row 2 \n")
print(c[1])
print("Print row 3 \n")
print(c[2])
print(c[1:3,:]) # this is using a slicing operation on the matrix instead of posting it separately

Numpy rows 2 # 3 in 'c' 

print row 2 

[5 6 7 8]
Print row 3 

[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]


#### 3) Print the values in the 2nd row and in cols 1 & 3

In [22]:
# Print the values in the 2nd row and in cols 1 & 3
print("2nd row column 1")
print(c[1,0])
print("2nd row column 3")
print(c[1,2])

2nd row column 1
5
2nd row column 3
7


#### 4) Perform a scalar multiplication of c with 4

In [23]:
# Perform a scalar multiplication of c with 4
scalr_mul = np.multiply(c,4)
print(scalr_mul)

[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]]


#### 5) Transpose c

In [25]:
# Transpose c
transpose_c = np.transpose(c)
print(transpose_c)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### 6) Reshape c to a 4 x 3 array
What is the difference between the transpose and reshape operations?

In [26]:
# Reshape c to a 4 x 3 array
reshape_c = np.reshape(c, (4,3))
print(reshape_c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## reshape is the wrap text of re-ordering!

#### 7) Perform an element-wise multiplication of the reshaped c and transposed c

In [28]:
# Perform an element-wise multiplication of the reshaped c and transposed c
element_wise = reshape_c * transpose_c
print(element_wise)

[[  1  10  27]
 [  8  30  60]
 [ 21  56  99]
 [ 40  88 144]]


### Random
Random number generation plays a crucial role in configuring and evaluating many numerical and machine learning algorithms. Whether it's for randomly initializing weights in a neural network, splitting data into random subsets, or shuffling a dataset, the ability to generate random numbers (specifically repeatable pseudo-random numbers) is vital.

#### 8) Create a half hourly power profile for 1 year filled with random numbers between 0 and 50

In [40]:
# create a half hourly power profile for 1 year filled with random numbers between 0 and 50
half_hour = np.random.uniform(0, 50, size=(48*365))
print(half_hour)

[20.9882344  25.64582366 40.82520592 ... 45.25738404 21.35104112
 22.83943387]


#### 9) Reshape the array into daily half hour profiles

In [41]:
# reshape the array into daily half hour profiles
forty8 = np.reshape(half_hour, (48,365))
#forty8 = np.reshape(half_hour, (48,-1)) <- if you don't know how many hours there are

print(forty8)

[[20.9882344  25.64582366 40.82520592 ... 19.7781486  15.44674883
  27.11208816]
 [ 2.54971507  9.17082391 11.17097333 ... 32.15107476  0.44253134
  30.01621384]
 [19.95346601  8.42801416 25.3222701  ...  8.62585483 14.49261329
  24.10537135]
 ...
 [46.37568634 34.24683675 17.20995213 ... 34.54703549 33.21708302
  19.00342772]
 [39.44347243 38.16839894 43.13274431 ... 10.873568   38.49097314
   6.99210653]
 [ 2.87965716 33.66604745 39.7236598  ... 45.25738404 21.35104112
  22.83943387]]


#### 10) convert this array to energy

In [37]:
# convert to energy
en48 = forty8/2
print(en48)

[[15.73331079  0.46581567  9.36245973 ... 16.65988984  4.07132141
  16.71915271]
 [15.48542072 20.05102879 23.93040298 ... 11.19163161 23.46100242
  21.41814584]
 [18.9577771   3.18341604 11.05804431 ... 11.45585232  7.52166774
  14.96715045]
 ...
 [13.56740603 23.21774009  4.01358539 ...  9.23061254 14.51264192
   5.60674649]
 [ 9.16444389 22.37336694 15.7932582  ... 21.13430718  5.93356245
   0.76182992]
 [ 8.54060967 15.67724712 20.9462793  ... 23.88054602  7.2527558
  13.41349839]]


  
#### Animation and Code Sources  

Numpy GIF: <a href="https://matteding.github.io/images/broadcasting-3d-scalar.gif">Matt Eding</a>  
